src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Recent_Payment__c</fullName>
        <label>Recent Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectContactController.cls
public class ProjectContactController {
    List<Contact> contacts = new List<Contact>();

    public Decimal paymentAmount{get;set;}
    public Date paymentDate{get;set;}
   
    public List<Contact> getContacts() {
  
        contacts= [SELECT Name,Total_Amount__c,Recent_Payment__c,
                   (
                       SELECT Payment_Amount__c, Payment_Date__c From Payments__r order by Payment_Date__c desc
                   ) 
                   FROM Contact where ID IN (SELECT Contact__c FROM Payment__c)
                  ];
                  
        return contacts;
    }
    
    public PageReference Save()  {
        System.debug('****** updated contacts, before insert: ' + contacts.get(1).Payments__r);  
        List<Payment__c> updatePaymentList = new List<Payment__c>();
        for(Contact c : contacts)   {
            updatePaymentList.addAll(c.Payments__r);    
        }
        update updatePaymentList;
        
        return null;  
    }
}